// views/pages/auth/Login.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import { button, card, field } from '@/js/ui'

export default function Login() {
  /*
   * `useForm` holds the field values, the submit state, and the errors the
   * server flashed back. `errors` here is Inertia's own — it reads the shared
   * `errors` prop that app/inertia.py populates from the session, so a failed
   * POST redirects back and the messages are simply present on the next
   * render. Nothing on this page inspects a response.
   */
  const { data, setData, post, processing, errors, reset } = useForm({
    email: '',
    password: '',
  })

  function submit(event: FormEvent) {
    event.preventDefault()
    post('/login', {
      // Never leave a password in component state after a failed attempt.
      onFinish: () => reset('password'),
    })
  }

  return (
    <>
      <Head title="Sign in" />

      <form className={card} onSubmit={submit} noValidate>
        <h1 className="text-2xl font-semibold tracking-tight">Sign in</h1>

        <label className={field.wrap}>
          <span className={field.label}>Email</span>
          <input
            type="email"
            className={field.input}
            value={data.email}
            onChange={(event) => setData('email', event.target.value)}
            autoComplete="username"
            autoFocus
          />
          {errors.email && <em className={field.error}>{errors.email}</em>}
        </label>

        <label className={field.wrap}>
          <span className={field.label}>Password</span>
          <input
            type="password"
            className={field.input}
            value={data.password}
            onChange={(event) => setData('password', event.target.value)}
            autoComplete="current-password"
          />
          {errors.password && <em className={field.error}>{errors.password}</em>}
        </label>

        <button type="submit" className={button.solid} disabled={processing}>
          {processing ? 'Signing in…' : 'Sign in'}
        </button>

        <p className="text-sm text-zinc-600 dark:text-zinc-400">
          No account yet?{' '}
          <Link href="/register" className="underline underline-offset-4 hover:text-brand">
            Create one
          </Link>
          .
        </p>
      </form>
    </>
  )
}

// views/pages/auth/Login.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import { useForm } from '@inertiajs/vue3'
import type { SharedProps } from '@/types'

defineProps<SharedProps>()

const form = useForm({ email: '', password: '' })

function submit() {
  form.post('/login', {
    onFinish: () => form.reset('password'),
  })
}
</script>

<template>
  <Head title="Sign in" />

  <form class="relative" @submit.prevent="submit" noValidate>
    <h1 class="text-2xl font-semibold tracking-tight text-zinc-900">
      Sign in
    </h1>
    <p class="mt-1 text-sm text-zinc-600">
      Continue where you left off. This is the Vue twin's sign-in form.
    </p>

    <label class="mt-5 block">
      <span class="text-sm font-medium text-zinc-700">Email</span>
      <input
        v-model="form.email"
        type="email"
        name="email"
        autocomplete="username"
        class="mt-1 block w-full rounded-md border border-zinc-300 px-3 py-2 text-sm shadow-sm focus:border-brand focus:outline-none focus:ring-2 focus:ring-brand/10"
      />
      <em v-if="form.errors.email" class="text-sm text-red-600">
        {{ form.errors.email }}
      </em>
    </label>

    <label class="mt-4 block">
      <span class="text-sm font-medium text-zinc-700">Password</span>
      <input
        v-model="form.password"
        type="password"
        name="password"
        autocomplete="current-password"
        class="mt-1 block w-full rounded-md border border-zinc-300 px-3 py-2 text-sm shadow-sm focus:border-brand focus:outline-none focus:ring-2 focus:ring-brand/10"
      />
      <em v-if="form.errors.password" class="text-sm text-red-600">
        {{ form.errors.password }}
      </em>
    </label>

    <button
      type="submit"
      :disabled="form.processing"
      class="mt-6 w-full rounded-md bg-brand px-3 py-2 text-sm font-medium text-white shadow-sm hover:bg-brand/90 disabled:opacity-50"
    >
      {{ form.processing ? 'Signing in…' : 'Sign in' }}
    </button>

    <p class="mt-4 text-sm text-zinc-600">
      New here?{' '}
      <Link href="/register" class="font-medium text-brand underline-offset-4 hover:underline">
        Create an account
      </Link>
      .
    </p>
  </form>
</template>
